### ISSUE TITLE
Should the question mark be in the route path?

### ISSUE THREAD

**Issue by IamSmith** [clocklimited/cf-crud-service-api-builder#6]
https://github.com/clocklimited/cf-crud-service-api-builder/blob/master/endpoints/put.js#L9

**Comment by bengourley** [comment]
Yeah it means the `:id` parameter is optional. See http://expressjs.com/en/guide/routing.html.

**Comment by bengourley** [comment]
Better detail here: https://www.npmjs.com/package/path-to-regexp#suffixed-parameters

**Comment by IamSmith** [comment]
Thanks @bengourley
